language: java
dist: xenial

stages:
  - name: build

jobs:
  include:
    - stage: build
      script:
        - ./gradlew check
        - ./gradlew chocol8:jar swing-app:distZip

before_deploy:
  - export CHOCOL8_JAR_FILE=$(ls build/chocol8/libs/*.jar)
  - export SWING_ZIP_FILE=$(ls build/swing-app/distributions/*.jar)

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  file:
    - ${RELEASE_JAR_FILE}
    - ${SWING_ZIP_FILE}
  skip_cleanup: true
  overwrite: true
  on:
    repo: faruh100/Chocol8-CHIP
    branch: master
    tags: true