os: linux
language: java
dist: xenial

stages:
  - name: build

jobs:
  include:
    - stage: build
      script:
        - ./gradlew check
        - ./gradlew chocol8:jar swing-app:distZip
        - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - export CHOCOL8_JAR_FILE=$(ls build/chocol8/libs/*.jar)
  - export SWING_ZIP_FILE=$(ls build/swing-app/distributions/*.jar)

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  file:
    - ${RELEASE_JAR_FILE}
    - ${SWING_ZIP_FILE}
  cleanup: false
  overwrite: true
  on:
    repo: faruh100/Chocol8-CHIP
    branch: master
    tags: true